"""Add Model

Revision ID: 27151b6a8831
Revises: 9c532ea58d31
Create Date: 2025-05-04 10:44:03.298402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27151b6a8831'
down_revision = '9c532ea58d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
