"""Add Model

Revision ID: 9c532ea58d31
Revises: 170d91e08768
Create Date: 2025-05-04 10:39:23.659331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c532ea58d31'
down_revision = '170d91e08768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('post')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reply_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               nullable=True)
        batch_op.create_foreign_key(None, 'discussion_room', ['room_id'], ['id'])
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.drop_column('reply_id')
        batch_op.drop_column('role')
        batch_op.drop_column('username')
        batch_op.drop_column('room_id')

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.create_table('reply',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['discussion_room.id'], name='reply_room_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name='reply_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reply_pkey')
    )
    # ### end Alembic commands ###
