"""Add Model

Revision ID: 9e31ac696176
Revises: ebac018e010e
Create Date: 2025-03-30 21:34:21.602726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e31ac696176'
down_revision = 'ebac018e010e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enrollment_date', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('enrollment_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('enrollment_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('enrollment_date')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
