"""Add Model

Revision ID: c8e445c18993
Revises: f3c3b047d31d
Create Date: 2025-03-30 14:19:43.198357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e445c18993'
down_revision = 'f3c3b047d31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('sur_name', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=7), nullable=True),
    sa.Column('enrollment_date', sa.DateTime(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('educators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sur_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educators', schema=None) as batch_op:
        batch_op.drop_column('sur_name')
        batch_op.drop_column('first_name')

    op.drop_table('students')
    # ### end Alembic commands ###
